# config/trainer/default.yaml
_target_: pytorch_lightning.Trainer
devices: [0]
num_nodes: 1
strategy: 'ddp'
min_epochs: 1
max_epochs: 200
gradient_clip_val: 0.5
accumulate_grad_batches: 4
num_sanity_val_steps: 5
check_val_every_n_epoch: 1
log_every_n_steps: 10
limit_train_batches: 1.0
limit_val_batches: 25
limit_test_batches: 1.0
profiler: "simple"
precision: ${precision}