# config/logger/default.yaml
in_use: ['tensorboard']
tensorboard:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: '${hydra:runtime.cwd}/logs/tensorboard'
  name: ${exp_name}
  default_hp_metric: False

wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${exp_name}
  project: BoxDreamer
  save_dir: '${hydra:runtime.cwd}/logs/wandb/${exp_name}/${mode}'
  offline: True
  id: null
  version: null

neptune:
  tags: ["best_model"]

csv_logger:
  save_dir: "."
