# config/config.yaml
defaults:
  - trainer: test
  - model: transformer
  - datamodule: test
  - callbacks: default
  - logger: default
  - hydra: default

seed: 42
max_epochs: 500
pretrain_name: boxdreamer
exp_name: boxdreamer_train
mode: 'test'
resume: False
use_pretrained: True
mask_bg: True
precision: "bf16"
image_size: 224
patch_size: 14
length: 6 # ref len + query len (1)
coordinate: 'object' # 'first_camera' or 'object' or 'optical_center'
pose_representation: 'bb8' # plucker or bb8 or vector
bbox_representation: 'heatmap' # heatmap or voting or cornernet
