# config/datamodule/onepose.yaml
_target_: src.datamodules.BoxDreamer_datamodule.BoxDreamerDataModule
train_datasets: [LINEMOD]
val_datasets: [LINEMOD]
test_datasets: [LINEMOD]
dataset_name: ["${datamodule.train_datasets}", "${datamodule.val_datasets}", "${datamodule.test_datasets}"]
batch_size: 22
num_workers: 8
pin_memory: True

# Shared base configuration for all datasets
base_config: &base_config
  image_size: ${image_size}
  length: ${length}
  dynamic_length: False
  stride: [1, 10]  # Default stride, can be overridden
  dynamic_stride: False
  random_stride: False
  uniform_sampling: True  # Default sampling method
  fps_sampling: False  # Default sampling method
  pose_augmentation: False
  mask_augmentation: False
  intri_augmentation: False
  compute_optical: True
  max_norm: False
  precision: ${precision}
  coordinate: ${coordinate}
  use_bbox: True
  use_mask: False
  mask_bg: ${mask_bg}
  pose_representation: ${pose_representation}
  bbox_representation: ${bbox_representation}

  augmentation: # only used for training set
    rgb_augmethods: ['dark', 'mobile'] # 'YCBAug', 'FDA' or null
    obj_truncation_ratio: 0.3
    obj_mask_ratio: 0.3
    enable_image_rotation: False


# Dataset-specific configurations
LINEMOD:
  name: 'LINEMOD'
  config:
    base:
      <<: *base_config
    root: "${hydra:runtime.cwd}/data/lm"
    cat_filter: null # ['cat', 'duck', 'benchvise', 'camera', 'driller'] #, 'lamp', 'eggbox', 'glue']
    model_suffix: null
    reference_suffix: null

LINEMODO:
  name: 'LINEMODO'
  config:
    base:
      <<: *base_config
    root: "${hydra:runtime.cwd}/data/lmo"
    cat_filter: null # ['cat']
    model_suffix: null
    reference_suffix: null

YCBV:
  name: 'YCBV'
  config:
    base:
      <<: *base_config
    root: "${hydra:runtime.cwd}/data/ycbv"
    cat_filter: ['061_foam_brick']
    model_suffix: null
    reference_suffix: null

MOPED:
  name: 'MOPED'
  config:
    base:
      <<: *base_config
      stride: [1, 5]  # Overridden for MOPED
      uniform_sampling: True  # Overridden for MOPED
      fps_sampling: False  # Overridden for MOPED
    root: "${hydra:runtime.cwd}/data/moped_preprocessed"
    cat_filter: null  # ['test-toy_plane-00', 'test-toy_plane-01', 'test-toy_plane-02', 'test-toy_plane-03', 'test-toy_plane-04']
    model_suffix: null
    reference_suffix: null

CO3D:
  name: 'CO3D'
  config:
    base:
      <<: *base_config
      stride: [1, 20]  # Overridden for CO3D
    root: "${hydra:runtime.cwd}/data"
    model_suffix: null
    reference_suffix: null

OnePose:
  name: 'OnePose'
  config:
    base:
      <<: *base_config
    root: "${hydra:runtime.cwd}/data/onepose"
    cat_filter: null # ['0557']
    model_suffix: null
    reference_suffix: null

OnePose_Lowtexture:
  name: 'OnePose'
  config:
    base:
      <<: *base_config
      stride: [5, 25]  # Overridden for OnePose
    root: "${hydra:runtime.cwd}/data/onepose-lowtexture"
    cat_filter: null
    model_suffix: null
    reference_suffix: null

Objaverse:
  name: 'Objaverse'
  config:
    base:
      <<: *base_config
      stride: [1, 5]  # Overridden for Objaverse
      uniform_sampling: True  # Overridden for Objaverse
      fps_sampling: True  # Explicitly set for Objaverse
    subdir_num: 100
    root: "${hydra:runtime.cwd}/data/objaverse"
    model_suffix: null
    reference_suffix: null
