metrics_list: ['pose_error', "ADD", "proj2d"] # "ADD", "proj2d"
point_cloud_rescale: 1
t_scale: 'm' # null ## 'm' # if val co3d, this should set to null
pose_error:
  pnp_reprojection_error: 5
  pose_thresholds: [1, 3, 5, 10, 15, 20, 30]
  use_pycolmap_ransac: False
  use_obj_mask: True
  use_conf_mask: False
  top_k: 2000
proj2d:
  proj2d_thres: 5
